"""
CrewAI Framework Adapter for AgentPort (OpenGAP).
Transforms canonical agent definitions into CrewAI multi-agent teams with sequential role delegation,
agents.yaml, tasks.yaml, and Crew definitions.
"""
import json
from typing import Dict, Any, List
from adapters.adapter_base import BaseAdapter, AdapterResult

class CrewAIAdapter(BaseAdapter):
    @property
    def framework_name(self) -> str:
        return "CrewAI"

    def transform(self, canonical_data: Dict[str, Any]) -> AdapterResult:
        warnings: List[str] = []
        portable_fields: List[str] = [
            "name",
            "version",
            "identity (as Backstory)",
            "purpose (as Goal)",
            "roles (as Crew Roles)",
            "tool_definitions",
            "sequential_duty_flow"
        ]
        framework_specific_fields: List[str] = [
            "crewai_process_sequential",
            "memory_storage_provider",
            "task_expected_output_contracts",
            "allow_delegation_flags",
            "agent_yaml_definitions"
        ]

        manifest = canonical_data.get("manifest", {})
        soul = canonical_data.get("soul", {})
        tools = canonical_data.get("tools", [])

        agent_name = manifest.get("name", "agent-port")
        role_title = f"{agent_name.capitalize().replace('-', ' ')} Governor"
        goal = "Deterministically enforce behavioral contracts, verify tool requests, and maintain zero-trust role separation."
        backstory = f"""{soul.get('identity', '')}
{soul.get('personality', '')}
Values: {soul.get('values', '')}"""
        single_line_backstory = backstory.replace('\n', ' ')

        # Generate CrewAI Agents YAML
        agents_yaml = f"""# CrewAI Agents Specification generated from OpenGAP
{agent_name}_governor:
  role: >
    {role_title}
  goal: >
    {goal}
  backstory: >
    {single_line_backstory}
  verbose: true
  allow_delegation: false
  max_iter: 15

maker_specialist:
  role: Action Proposal Author
  goal: Propose secure actions, draft parameter payloads, and formulate tool requests
  backstory: Operates as the creative proposal engine while strictly blocked from self-certification.
  allow_delegation: false

checker_specialist:
  role: Compliance and Risk Verifier
  goal: Evaluate proposals against OpenGAP safety policies and grant clearance tokens
  backstory: Rigorous policy gatekeeper ensuring dual-control integrity and schema adherence.
  allow_delegation: false
"""

        # Generate CrewAI Tasks YAML
        tasks_yaml = f"""# CrewAI Tasks Specification
propose_action_task:
  description: >
    Evaluate the incoming system request and draft an actionable proposal.
  expected_output: >
    Structured action proposal with designated tool targets and required parameters.
  agent: maker_specialist

verify_compliance_task:
  description: >
    Inspect the drafted action proposal, run risk_check, and confirm Maker/Checker separation.
  expected_output: >
    Formal verdict (ALLOW, REQUIRE_APPROVAL, or BLOCK) with cryptographic signature.
  agent: checker_specialist

execute_action_task:
  description: >
    Execute the verified operation only if clearance status is APPROVED.
  expected_output: >
    Execution telemetry and payload audit record.
  agent: {agent_name}_governor
"""

        python_crew_code = f'''# Generated by AgentPort Export Engine for CrewAI
from crewai import Agent, Crew, Process, Task
from crewai.tools import BaseTool
from typing import Type
from pydantic import BaseModel, Field

# Define tools
'''
        for tool in tools:
            tool_fn = tool.get("name", "tool")
            python_crew_code += f'''class {tool_fn.title().replace('_', '')}Input(BaseModel):
    query: str = Field(description="{tool.get('description', '')}")

class {tool_fn.title().replace('_', '')}Tool(BaseTool):
    name: str = "{tool_fn}"
    description: str = "{tool.get('description', '')}"
    args_schema: Type[BaseModel] = {tool_fn.title().replace('_', '')}Input

    def _run(self, query: str) -> str:
        return f"Executing {tool_fn} under OpenGAP policy rules"

'''

        python_crew_code += f'''# Instantiate Crew Agents
governor = Agent(
    role="{role_title}",
    goal="{goal}",
    backstory="""{backstory}""",
    verbose=True,
    allow_delegation=False,
    tools=[{", ".join([t.get('name').title().replace('_', '') + 'Tool()' for t in tools])}]
)

# Crew instantiation with Sequential Process enforcing Separation of Duties
agentport_crew = Crew(
    agents=[governor],
    tasks=[], # Populated from tasks.yaml
    process=Process.sequential,
    verbose=True,
    memory=True
)
'''

        artifact_bundle = {
            "framework": "crewai",
            "agents_yaml": agents_yaml,
            "tasks_yaml": tasks_yaml,
            "crew_python_code": python_crew_code,
            "configuration": {
                "process": "sequential",
                "memory_enabled": True,
                "allow_delegation": False
            }
        }

        return AdapterResult(
            framework="CrewAI",
            success=True,
            artifact=json.dumps(artifact_bundle, indent=2),
            portable_fields=portable_fields,
            framework_specific_fields=framework_specific_fields,
            warnings=warnings,
            raw_manifest=artifact_bundle
        )
