"""
Lyzr Framework Adapter for AgentPort (OpenGAP).
Transforms canonical agent definitions into Lyzr Automata agents, Lyzr Agent API payloads,
persona prompts, and tool integrations.
"""
import json
from typing import Dict, Any, List
from adapters.adapter_base import BaseAdapter, AdapterResult

class LyzrAdapter(BaseAdapter):
    @property
    def framework_name(self) -> str:
        return "Lyzr"

    def transform(self, canonical_data: Dict[str, Any]) -> AdapterResult:
        warnings: List[str] = []
        portable_fields: List[str] = [
            "name",
            "version",
            "persona_prompt",
            "behavior_instructions",
            "tool_call_interfaces",
            "security_boundaries"
        ]
        framework_specific_fields: List[str] = [
            "lyzr_agent_api_payload",
            "automata_task_graph",
            "lyzr_knowledge_base_bindings",
            "lyzr_session_state_config"
        ]

        manifest = canonical_data.get("manifest", {})
        soul = canonical_data.get("soul", {})
        tools = canonical_data.get("tools", [])

        agent_name = manifest.get("name", "agent-port")
        persona_prompt = f"""You are {agent_name} (v{manifest.get('version', '1.0.0')}).
Role: Autonomous Systems Governance & Verification Agent.
Identity: {soul.get('identity', '')}
Personality: {soul.get('personality', '')}
Values: {soul.get('values', '')}
Style: {soul.get('communication_style', '')}
Principles: {soul.get('behavioral_principles', '')}
"""

        # Map tools for Lyzr Automata
        lyzr_tool_configs = []
        for t in tools:
            lyzr_tool_configs.append({
                "tool_name": t.get("name"),
                "tool_type": "custom_python_tool",
                "description": t.get("description"),
                "permission_role": t.get("permission_level")
            })

        # Lyzr Python code representation
        lyzr_code = f'''# Generated by AgentPort Export Engine for Lyzr Automata
from lyzr_automata import Agent, Task
from lyzr_automata.tools import Tool
from lyzr_automata.ai_models.openai import OpenAIModel

# Initialize underlying LLM model for Lyzr
llm_model = OpenAIModel(
    api_key="OPTIONAL_ENV_KEY",
    parameters={{"model": "gpt-4o", "temperature": 0.2}}
)

# Instantiate Lyzr Agent
{agent_name.replace('-', '_')} = Agent(
    role="{manifest.get('name')} Verifier",
    prompt_persona="""{persona_prompt.strip()}""",
    model=llm_model
)

# Lyzr Policy Enforcement Task
governance_task = Task(
    name="Verify And Enforce Contract",
    agent={agent_name.replace('-', '_')},
    output_type="json",
    input_type="text",
    model=llm_model,
    instructions="Process input, enforce Maker/Checker boundaries, and record audit evidence."
)
'''

        # Lyzr Agent API payload for cloud deployment
        api_payload = {
            "agent_id": f"lyzr-{agent_name}-v1",
            "name": manifest.get("name"),
            "role": "Autonomous Systems Governance & Verification Agent",
            "description": manifest.get("description"),
            "system_prompt": persona_prompt.strip(),
            "tools": lyzr_tool_configs,
            "features": {
                "memory": True,
                "rag": False,
                "role_separation": True
            }
        }

        artifact_bundle = {
            "framework": "lyzr",
            "api_payload": api_payload,
            "lyzr_python_code": lyzr_code,
            "export_notes": "Lyzr Automata definition configured with custom persona prompt and tool signatures."
        }

        return AdapterResult(
            framework="Lyzr",
            success=True,
            artifact=json.dumps(artifact_bundle, indent=2),
            portable_fields=portable_fields,
            framework_specific_fields=framework_specific_fields,
            warnings=warnings,
            raw_manifest=artifact_bundle
        )
