"""
OpenAI Agents SDK Adapter for AgentPort (OpenGAP).
Transforms canonical agent definitions into OpenAI Agents SDK representations with function schemas,
handoffs, and strict output contracts.
"""
import json
from typing import Dict, Any, List
from adapters.adapter_base import BaseAdapter, AdapterResult

class OpenAIAdapter(BaseAdapter):
    @property
    def framework_name(self) -> str:
        return "OpenAI Agents SDK"

    def transform(self, canonical_data: Dict[str, Any]) -> AdapterResult:
        warnings: List[str] = []
        portable_fields: List[str] = [
            "name",
            "version",
            "description",
            "identity",
            "values",
            "behavior_rules",
            "tool_schemas"
        ]
        framework_specific_fields: List[str] = [
            "openai_model_spec",
            "handoff_routing_functions",
            "strict_json_schema_enforcement",
            "runner_loop_parameters"
        ]

        manifest = canonical_data.get("manifest", {})
        soul = canonical_data.get("soul", {})
        agents = canonical_data.get("agents", "")
        duties = canonical_data.get("duties", "")
        tools = canonical_data.get("tools", [])

        agent_name = manifest.get("name", "agent-port").replace("-", "_")
        description = manifest.get("description", "OpenGAP Agent")

        # Compile OpenAI formatted function tools
        openai_tools = []
        for tool in tools:
            input_schema = tool.get("input_schema", {})
            # Ensure OpenAI strict parameter compliance (additionalProperties: false)
            clean_schema = {
                "type": "object",
                "properties": input_schema.get("properties", {}),
                "required": input_schema.get("required", []),
                "additionalProperties": False
            }
            openai_tools.append({
                "type": "function",
                "function": {
                    "name": tool.get("name"),
                    "description": tool.get("description"),
                    "parameters": clean_schema,
                    "strict": True
                }
            })

        # Generate OpenAI Agents SDK Python implementation code
        instructions_text = f"""You are {manifest.get('name', 'agent-port')} (v{manifest.get('version', '1.0.0')}).
Description: {description}

IDENTITY & PERSONALITY:
{soul.get('identity', '')}
{soul.get('personality', '')}

COMMUNICATION & VALUES:
{soul.get('communication_style', '')}
{soul.get('values', '')}

OPERATING CONSTRAINTS:
1. Always enforce Maker/Checker role segregation.
2. Inquire with `risk_check` prior to state mutations.
3. Every decision must provide explicit Decision, Inputs, and Limits.
"""

        python_code = f'''# Generated by AgentPort Export Engine for OpenAI Agents SDK
from agents import Agent, Runner, function_tool
from typing import Dict, Any, List

# Target Agent definition
{agent_name} = Agent(
    name="{manifest.get('name', 'agent-port')}",
    model="gpt-4o",
    instructions="""{instructions_text.strip()}""",
    tools=[
'''
        for t in openai_tools:
            fn = t["function"]
            python_code += f'        # Tool: {fn["name"]}\n'
            python_code += f'        # {fn["description"]}\n'

        python_code += f'''    ],
    temperature=0.1
)

# Separation of Duties Handoff Definitions
maker_agent = Agent(
    name="{manifest.get('name')}_maker",
    instructions="Responsible for drafting proposals and actions. Cannot self-certify."
)

checker_agent = Agent(
    name="{manifest.get('name')}_checker",
    instructions="Responsible for independent policy review and authorization. Cannot draft proposals."
)

handoff_fn = {{
    "transfer_to_checker": checker_agent,
    "transfer_to_maker": maker_agent
}}
'''

        artifact_bundle = {
            "framework": "openai_agents_sdk",
            "agent_spec": {
                "name": manifest.get("name"),
                "version": manifest.get("version"),
                "instructions": instructions_text.strip(),
                "model": "gpt-4o",
                "tools": openai_tools,
                "tool_choice": "auto"
            },
            "python_sdk_source": python_code,
            "export_notes": "Compiled with OpenAI Agents SDK strict tools mode and dual-agent handoffs."
        }

        return AdapterResult(
            framework="OpenAI Agents SDK",
            success=True,
            artifact=json.dumps(artifact_bundle, indent=2),
            portable_fields=portable_fields,
            framework_specific_fields=framework_specific_fields,
            warnings=warnings,
            raw_manifest=artifact_bundle
        )
